version: '3.7'

services:

  mockapp:
    build: ./MockApp/
    container_name: mockapp
    volumes:
      - ./MockApp/src:/base
      - ./MockApp/state:/state
    ports: 
      - "8080:8080"
      - "8090:90"
    environment:
      - "WATCH=true"
      - "STATEFILE=default.json"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 1s
      retries: 100
    networks: 
      - mockservice            

  build:
    image: node:16.5-alpine
    volumes:
      - ./:/app
    command: npm run build --prefix /app

  k6:
    depends_on:
      build:
        condition: service_completed_successfully
      mockapp:
        condition: service_healthy      
    image: loadimpact/k6
    volumes:
      - ./dist:/dist
    command: run /dist/tests.js --config /dist/options/smoke.json --http-debug
    environment:
      - APP_DOMAIN=http://mockapp:8080      
    networks: 
      - mockservice        

networks:
    mockservice:
        name: mockservice    